create workpacks as project subunits

diff --git a/bin/org-anize b/bin/org-anize
--- a/bin/org-anize
+++ b/bin/org-anize
@@ -105,6 +105,7 @@ org-dir(){
 ##----------------------------------------------------------------------------##
 # init
 org-init(){
+    [ -z "$PRO" ] && { echo 'project name required'; exit 1; }
     PRO_DATE=$(date +"%D")
     mkdir -p $PRO;
 
@@ -124,8 +125,45 @@ org-init(){
         done
     fi;
 
-    echo "Created $PRO_FILE";
+    echo "Created project [$PRO]";
 }
+
+##----------------------------------------------------------------------------##
+# init workpack
+org-workpack(){
+    WPK=$PRO
+    [ -z "$WPK" ] && { echo 'workpack name required'; exit 1; }
+    get-project
+
+    WPK_DATE=$(date +"%D")
+    mkdir -p $WPK;
+
+    for subdir in ${ORG_WPK_DIRS//:/ }; do
+        mkdir -p "$WPK/$subdir";
+    done
+
+    WPK_FILE=$WPK/$WPK$ORG_WPK_SUF; # create *-workpack.org at top-level
+    if [ ! -e $WPK_FILE ]; then
+        echo "$ORG_WPK_TPL" | while read -r line ; do
+            while [[ "$line" =~ (\$\{[a-zA-Z_][a-zA-Z_0-9]*\}) ]] ; do
+                LHS=${BASH_REMATCH[1]}
+                RHS="$(eval echo "\"$LHS\"")"
+                line=${line//$LHS/$RHS}
+            done
+            echo "$line" >> $WPK_FILE
+        done
+    fi;
+
+    echo "Created workpack [$WPK] in project [$PRO]";
+}
+
+# check if current dir is project
+get-project(){
+    ls *$ORG_PRO_SUF &>/dev/null || { echo "not inside a project"; exit 1; }
+    PROS=( *$ORG_PRO_SUF )
+    PRO=$(basename ${PROS[0]} $ORG_PRO_SUF)
+}
+
 
 ##----------------------------------------------------------------------------##
 # aliases - convenient for placing them in bashrc...
